CREATE TABLE assignments
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    driver_id     BIGINT,
    dispatcher_id BIGINT,
    check_list    BOOLEAN                                 NOT NULL,
    assigned_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_assignments PRIMARY KEY (id)
);

CREATE TABLE baggages
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    weight   INTEGER                                 NOT NULL,
    tag_code VARCHAR(255),
    fee      DECIMAL,
    CONSTRAINT pk_baggages PRIMARY KEY (id)
);

CREATE TABLE buses
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    plate    VARCHAR(255),
    capacity INTEGER                                 NOT NULL,
    status   VARCHAR(255),
    CONSTRAINT pk_buses PRIMARY KEY (id)
);

CREATE TABLE fare_rules
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    route_id           BIGINT,
    base_price         DECIMAL                                 NOT NULL,
    is_dynamic_pricing BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_fare_rules PRIMARY KEY (id)
);

CREATE TABLE route_stops
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stop_order     INTEGER                                 NOT NULL,
    route_id       BIGINT,
    origin_id      BIGINT,
    destination_id BIGINT,
    fare_rule_id   BIGINT,
    CONSTRAINT pk_routestops PRIMARY KEY (id)
);

CREATE TABLE routes
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(255),
    name VARCHAR(255),
    CONSTRAINT pk_routes PRIMARY KEY (id)
);

CREATE TABLE seats
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number  INTEGER                                 NOT NULL,
    type    SMALLINT,
    trip_id BIGINT,
    CONSTRAINT pk_seats PRIMARY KEY (id)
);

CREATE TABLE stops
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    city VARCHAR(255)                            NOT NULL,
    lat  FLOAT                                   NOT NULL,
    lng  FLOAT                                   NOT NULL,
    CONSTRAINT pk_stops PRIMARY KEY (id)
);

CREATE TABLE trips
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bus_id       BIGINT,
    route_id     BIGINT,
    date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    departure_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    arrival_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    trip_status  SMALLINT                                NOT NULL,
    CONSTRAINT pk_trips PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    email         VARCHAR(255),
    rols          SMALLINT,
    password_hash VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE assignments
    ADD CONSTRAINT FK_ASSIGNMENTS_ON_DISPATCHERID FOREIGN KEY (dispatcher_id) REFERENCES users (id);

ALTER TABLE assignments
    ADD CONSTRAINT FK_ASSIGNMENTS_ON_DRIVERID FOREIGN KEY (driver_id) REFERENCES users (id);

ALTER TABLE fare_rules
    ADD CONSTRAINT FK_FARE_RULES_ON_ROUTE FOREIGN KEY (route_id) REFERENCES routes (id);

ALTER TABLE route_stops
    ADD CONSTRAINT FK_ROUTESTOPS_ON_DESTINATIONID FOREIGN KEY (destination_id) REFERENCES stops (id);

ALTER TABLE route_stops
    ADD CONSTRAINT FK_ROUTESTOPS_ON_FARERULEID FOREIGN KEY (fare_rule_id) REFERENCES fare_rules (id);

ALTER TABLE route_stops
    ADD CONSTRAINT FK_ROUTESTOPS_ON_ORIGINID FOREIGN KEY (origin_id) REFERENCES stops (id);

ALTER TABLE route_stops
    ADD CONSTRAINT FK_ROUTESTOPS_ON_ROUTEID FOREIGN KEY (route_id) REFERENCES routes (id);

ALTER TABLE seats
    ADD CONSTRAINT FK_SEATS_ON_TRIPID FOREIGN KEY (trip_id) REFERENCES trips (id);

ALTER TABLE trips
    ADD CONSTRAINT FK_TRIPS_ON_BUSID FOREIGN KEY (bus_id) REFERENCES buses (id);

ALTER TABLE trips
    ADD CONSTRAINT FK_TRIPS_ON_ROUTEID FOREIGN KEY (route_id) REFERENCES routes (id);